server:
  port: 8082
spring:
  application:
    name: api-gate
  cloud:
    gateway:
      routes:
        - id: notes
          uri: http://localhost:8085/
          predicates:
            - Path=/notes/**